### ISSUE TITLE
pip-date script fails under Windows

### ISSUE THREAD

**Issue by vuolter** [E3V3A/pip-date#2]
I tested the latest release available on PyPI.
The `pipbyday` script is working fine.

Debug log:
```
C:\>py -3 "c:\python3\scripts\pip-date"

Traceback (most recent call last):
  File "c:\python3\scripts\pip-date", line 194, in <module>
    pkg_mtime = yellow(pkg_mtime)
  File "c:\python3\scripts\pip-date", line 50, in yellow
    def yellow(text): return color(text, 33)            #
  File "c:\python3\scripts\pip-date", line 40, in color
    if sys.platform == "win32" and "xterm" not in os.getenv("TERM"):    # [xterm, xterm-color, xterm-256color]
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by E3V3A** [comment]
uh oh!  Thanks for reporting! :+1:   
I don't have a pure Windows python, so I just took a chance that it would work.

Can you please do the following: 
```bash
python3 -c "import sys; print(sys.platform);"
python3 -c 'import os; print(os.getenv("TERM"));'
```
alternatively do the same in the raw python3 interpreter. 

BTW. Does your windows console handle colors when running python programs?

If you don't know if you have color capability, please download and run [ColorTool](https://github.com/Microsoft/console/releases) from a CMD (or whatever you use to run python):

```bash
ColorTool.exe -c
```
(Should give you a color palette.)

**Comment by E3V3A** [comment]
@vuolter 
Try the updated package.
If there is still a problem please re-open issue.

**Comment by vuolter** [comment]
I'll retry later and let you know, thanks man. 😉

**Comment by vuolter** [comment]
@E3V3A Hi, I tested the script and it's working quite well now, just formatting is a bit tricky to read due the missing console color capability. Maybe using https://pypi.org/project/colorama/ would fix that side...
```
C:\>py -3 -c "import sys; print(sys.platform);"
win32

C:\>py -3 -c "import os; print(os.getenv('TERM'));"
None
```
Script log:
```
C:\>python "C:\python3\Scripts\pip-date"

[31mSkipping Bad Path of:[0m wrapt:   c:\python3\lib\site-packages/wrapt-1.10.11
[31mSkipping Bad Path of:[0m tzlocal:         c:\python3\lib\site-packages/tzlocal-1.5.1
[31mSkipping Bad Path of:[0m thrift:  c:\python3\lib\site-packages/thrift-0.11.0
[31mSkipping Bad Path of:[0m simplejson:      c:\python3\lib\site-packages/simplejson-3.16.0
[31mSkipping Bad Path of:[0m pyxmpp2:         c:\python3\lib\site-packages/pyxmpp2-2.0.1
[31mSkipping Bad Path of:[0m pyjsparser:      c:\python3\lib\site-packages/pyjsparser-2.5.2
[31mSkipping Bad Path of:[0m pycparser:       c:\python3\lib\site-packages/pycparser-2.19
[31mSkipping Bad Path of:[0m lazy-object-proxy:       c:\python3\lib\site-packages/lazy_object_proxy-1.3.1
[31mSkipping Bad Path of:[0m jsmin:   c:\python3\lib\site-packages/jsmin-2.2.2
[31mSkipping Bad Path of:[0m Js2Py:   c:\python3\lib\site-packages/Js2Py-0.59
[31mSkipping Bad Path of:[0m htmlmin:         c:\python3\lib\site-packages/htmlmin-0.1.12
[31mSkipping Bad Path of:[0m Flask-Themes2:   c:\python3\lib\site-packages/Flask_Themes2-0.1.4
[31mSkipping Bad Path of:[0m Flask-Minify:    c:\python3\lib\site-packages/Flask_Minify-0.9
[31mSkipping Bad Path of:[0m Flask-Login:     c:\python3\lib\site-packages/Flask_Login-0.4.1
[31mSkipping Bad Path of:[0m Flask-Compress:  c:\python3\lib\site-packages/Flask_Compress-1.4.0
[31mSkipping Bad Path of:[0m Flask-Babel:     c:\python3\lib\site-packages/Flask_Babel-0.12.2
[31mSkipping Bad Path of:[0m easy-getch:      c:\python3\lib\site-packages/easy_getch-1.0.6
[31mSkipping Bad Path of:[0m blinker:         c:\python3\lib\site-packages/blinker-1.4
[31mSkipping Bad Path of:[0m pip-date:        c:\pip-date-master/pip_date-1.0.2

Package                Installed (cTime)      Modified (mTime)       Version            Inst     Prec   Type    Loc
-------------------------------------------------------------------------------------------------------------------
[1;49;34mappdirs[0m                [0;49;96m2018-12-02  05:17:29[0m                          1.4.3              pip             wheel   sys
argon2-cffi            [0;49;96m2018-12-02  15:43:30[0m                          18.3.0             pip             wheel   sys
asn1crypto             [0;49;96m2018-12-02  10:03:43[0m                          0.24.0             pip             wheel   sys
astroid                [0;49;96m2018-12-02  05:16:45[0m                          2.1.0              pip             wheel   sys
attrs                  [0;49;96m2018-12-02  05:17:29[0m                          18.2.0             pip             wheel   sys
Babel                  [0;49;96m2018-12-02  10:04:30[0m                          2.6.0              pip             wheel   sys
backports.functools-lru-cache   [0;49;96m2018-12-02  10:03:34[0m                          1.5                pip             wheel   sys
beautifulsoup4         [0;49;96m2018-12-02  10:05:47[0m                          4.6.3              pip             wheel   sys
black                  [0;49;96m2018-12-02  05:17:30[0m   [33m2018-12-02  05:17:31[0m   18.9b0             pip             wheel   sys
certifi                [0;49;96m2018-12-02  10:06:36[0m                          2018.11.29         pip             wheel   sys
cffi                   [0;49;96m2018-12-02  10:03:40[0m                          1.11.5             pip             wheel   sys
chardet                [0;49;96m2018-12-02  10:06:39[0m                          3.0.4              pip             wheel   sys
cheroot                [0;49;96m2018-12-02  10:03:36[0m   [33m2018-12-02  10:03:37[0m   6.5.2              pip             wheel   sys
Click                  [0;49;96m2018-12-02  05:17:28[0m                          7.0                pip             wheel   sys
colorama               [0;49;96m2018-12-02  05:16:04[0m                          0.4.1              pip             wheel   sys
colorlog               [0;49;96m2018-12-02  10:05:48[0m                          3.1.4              pip             wheel   sys
cryptography           [0;49;96m2018-12-02  10:03:47[0m                          2.4.2              pip             wheel   sys
Flask                  [0;49;96m2018-12-02  10:03:57[0m   [33m2018-12-02  10:03:58[0m   1.0.2              pip             wheel   sys
Flask-DebugToolbar     [0;49;96m2018-12-02  10:04:42[0m                          0.10.1             pip             wheel   sys
idna                   [0;49;96m2018-12-02  10:03:41[0m                          2.7                pip             wheel   sys
isort                  [0;49;96m2018-12-02  05:16:04[0m                          4.3.4              pip             wheel   sys
itsdangerous           [0;49;96m2018-12-02  10:03:49[0m                          1.1.0              pip             wheel   sys
Jinja2                 [0;49;96m2018-12-02  10:03:51[0m                          2.10               pip             wheel   sys
lesscpy                [0;49;96m2018-12-02  10:04:55[0m   [33m2018-12-02  10:04:56[0m   0.13.0             pip             wheel   sys
MarkupSafe             [0;49;96m2018-12-02  10:03:49[0m                          1.1.0              pip             wheel   sys
mccabe                 [0;49;96m2018-12-02  05:16:45[0m                          0.6.1              pip             wheel   sys
more-itertools         [0;49;96m2018-12-02  10:03:35[0m                          4.3.0              pip             wheel   sys
Pillow                 [0;49;96m2018-12-02  10:05:54[0m                          5.3.0              pip             wheel   sys
pip                    2018-11-20  14:05:33                          10.0.1             pip             wheel   sys
ply                    [0;49;96m2018-12-02  10:04:52[0m                          3.11               pip             wheel   sys
pycryptodomex          [0;49;96m2018-12-02  10:06:09[0m                          3.7.2              pip             wheel   sys
pycurl                 [0;49;96m2018-12-02  09:56:33[0m                          7.43.1             pip             wheel   sys
pylint                 [0;49;96m2018-12-02  05:17:27[0m                          2.2.2              pip             wheel   sys
pyOpenSSL              [0;49;96m2018-12-02  10:06:10[0m                          18.0.0             pip             wheel   sys
pytz                   [0;49;96m2018-12-02  10:04:10[0m                          2018.7             pip             wheel   sys
requests               [0;49;96m2018-12-02  10:06:42[0m                          2.20.1             pip             wheel   sys
semver                 [0;49;96m2018-12-02  10:05:45[0m                          2.8.1              pip             wheel   sys
Send2Trash             [0;49;96m2018-12-02  10:05:46[0m                          1.5.0              pip             wheel   sys
[1;49;34msetuptools[0m             2018-11-20  14:05:17                          39.0.1             pip             wheel   sys
[1;49;34msix[0m                    [0;49;96m2018-12-02  05:16:33[0m                          1.11.0             pip             wheel   sys
toml                   [0;49;96m2018-12-02  05:17:29[0m   [33m2018-12-02  05:17:30[0m   0.10.0             pip             wheel   sys
urllib3                [0;49;96m2018-12-02  10:06:41[0m                          1.24.1             pip             wheel   sys
Werkzeug               [0;49;96m2018-12-02  10:03:55[0m                          0.14.1             pip             wheel   sys
-------------------------------------------------------------------------------------------------------------------
  [31m▅[0m = ERROR (preventing package processing)
  [35m▅[0m = Bad / Non-Standard Installation Path
  [33m▅[0m = Possibly Multiple installations (differing file times)
  [0;49;96m▅[0m = Recently Changed / Installed (in last 7 days)
  [32m▅[0m = Non-PEM-compliant Version string (PEP-0440) | ~/.local install
  [1;49;34m▅[0m = A 'setuptools' dependency package
-------------------------------------------------------------------------------------------------------------------
Found 43 packages.

Done!
```

I almost forgot to mention that looks like scripts are not automatically removed when uninstalling the package from pip. 😞

**Comment by E3V3A** [comment]
@vuolter 
Hi Walter! 
Wow, sorry for crazy late delay. I've been quite busy with many other things, and manged to accidentally remove all my github notifications! So I really appreciate you reporting back. Will look into it again in a few days. In addition I have learnt a lot about how windows console does coloring and fonts. So the block I've chosen belong to a far out Unicode font, and is not visible in most fonts offered by windows conhost (cmd, powershell). 

So to get it straight, does colorama work on your device? 

BTW. What OS version and command shell are you using? Python version?
\Cheers!

**Comment by E3V3A** [comment]
@vuolter 
Also, all the packages shown with "bad path", how were they installed? 
(Seem too many of those...)

**Comment by E3V3A** [comment]
To uninstall all, it depends how it was installed: 

Docs say: 
```bash
# With or without "--user", depending on how it was installed
python setup.py develop --uninstall --user
```

Apparently, [that is a known pip/setuptools](https://github.com/pypa/pip/issues/5997) bug!

**Comment by E3V3A** [comment]
I think the uninstall bug has been fixed in pip, now. I removes everything in latest Linux Mint 19.1.
Also I'll see if I can test for any TERM, as native windows consoles never returns any TERM, unless in WSL or Cygwin, in which case it should be ok.
